# Generated by Django 4.0.4 on 2022-05-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='msg',
            field=models.CharField(default='NA', max_length=500),
        ),
    ]
