# Generated by Django 4.0.4 on 2022-05-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_contact_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='msg',
        ),
    ]
