# Generated by Django 4.0.4 on 2022-05-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_remove_contact_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='msg',
            field=models.CharField(default='', max_length=200),
        ),
    ]
