# Generated by Django 4.0.4 on 2022-05-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_contact_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(default='', max_length=5000)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=60)),
                ('address', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=40)),
                ('state', models.CharField(default='', max_length=40)),
                ('Zip_code', models.IntegerField(default=0)),
            ],
        ),
    ]
