# Generated by Django 4.0.4 on 2022-06-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
