# Generated by Django 4.0.4 on 2022-06-07 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_alter_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
